### ISSUE TITLE
One click global replacement

### ISSUE THREAD

**Issue by Yunmoyan** [MahmoudFawzyKhalil/obsidian-global-search-and-replace#12] opened 2023-07-29 13:39 UTC
Hello, is there a chance to add a global one-click replace all feature? I believe it would be meaningful.Thank you very much.

**Comment by MahmoudFawzyKhalil** [comment] 2023-07-30 13:57
Hello, this is a duplicate of #5 so I will close it here.

Thank you for your suggestion.

**Closed as not planned** 2023-07-30 13:57 UTC

**Comment by Yunmoyan** [comment] 2023-07-30 15:56
I have already understood, thanks for your response.
