### ISSUE TITLE
[FR] Replace All

### ISSUE THREAD

**Issue by mhellmeier** [MahmoudFawzyKhalil/obsidian-global-search-and-replace#11] opened 2023-07-01 09:20 UTC
As described in the features part of the `README.md`, a match can be replaced by either clicking on it or pressing enter. It would be great to add a new functionality "Replace All, replacing all findings in all files.

**Comment by MahmoudFawzyKhalil** [comment] 2023-07-01 20:08
Thank you for your request @mhellmeier. I am closing this as a duplicate of #5, you can thumbs up there or add a comment there if what it specified there is not exactly what you want.

**Closed as not planned by MahmoudFawzyKhalil** 2023-07-01 20:08 UTC
